-- create table
CREATE TABLE IF NOT EXISTS HACKATON_DETAILS(
        index int,
        hackathon_id text not null,
        hackathon_winner boolean,   
        hackathon_url_caller text,    
        project_title text,    
        project_likes int,   
        hackathon_name text,    
        project_subtitle text,   
        project_github_url text,  
        project_number_of_comments int,    
        team_size int,   
        project_creation_timestamp timestamp,     
        project_url text,   
        project_id text not null,   
        team text,   
        participant_id text not null,   
        _id text,   
        hackathon_number_of_prizes int,    
        hackathon_number_of_judges int,   
        hackathon_number_of_participants int,   
        hackathon_is_colocated boolean,   
        hackathon_has_ended boolean,   
        hackathon_url text,   
        hackathon_description_header text,    
        hackathon_prizes_total text,   
        has_projects boolean,    
        Country text,   
        participant_likes int,   
        participant_projects int,   
        participant_url text,  
        participant_name text,   
        participant_followers text,   
        participant_location text, 
        participant_bio text,
        participant_linkedin text,  
        participant_website text,   
        participant_github text,   
        participant_hackathons text,   
        participant_following text,   
        participant_number_of_skills int);

